[package]
name = "erl_parse"
version = "0.0.8"
description = "Erlang source code parser"
homepage = "https://github.com/sile/erl_parse"
repository = "https://github.com/sile/erl_parse"
readme = "README.md"
keywords = ["erlang", "parser"]
categories = ["parser-implementations"]
license = "MIT"
edition = "2024"
rust-version = "1.88"

[workspace]
members = ["examples/otp_conformance"]
resolver = "3"

[dependencies]
erl_tokenize = "0.11"

[dev-dependencies]
noprop = "0.2"
